from __future__ import annotations

ABNT_TYPE_GENERIC = "generic"
ABNT_TYPE_BOOK = "book"
ABNT_TYPE_CHAPTER = "chapter"
ABNT_TYPE_ARTICLE = "article"
ABNT_TYPE_THESIS = "thesis"
ABNT_TYPE_LEGAL = "legal"
ABNT_TYPE_ONLINE = "online"
ABNT_TYPE_INSTITUTIONAL_REPORT = "institutional_report"

ABNT_DOCUMENT_TYPES = {
    ABNT_TYPE_GENERIC,
    ABNT_TYPE_BOOK,
    ABNT_TYPE_CHAPTER,
    ABNT_TYPE_ARTICLE,
    ABNT_TYPE_THESIS,
    ABNT_TYPE_LEGAL,
    ABNT_TYPE_ONLINE,
    ABNT_TYPE_INSTITUTIONAL_REPORT,
}


__all__ = [
    "ABNT_DOCUMENT_TYPES",
    "ABNT_TYPE_ARTICLE",
    "ABNT_TYPE_BOOK",
    "ABNT_TYPE_CHAPTER",
    "ABNT_TYPE_GENERIC",
    "ABNT_TYPE_INSTITUTIONAL_REPORT",
    "ABNT_TYPE_LEGAL",
    "ABNT_TYPE_ONLINE",
    "ABNT_TYPE_THESIS",
]
